### ISSUE TITLE
请问怎么封装echart.js

### ISSUE THREAD

**Issue by 915479996** [Billiballa/grafana-echarts#12]
在用以下代码时：
`var color = new echarts.graphic.LinearGradient(0, 0, 1, 0, [{
        offset: 0,
        color: '#5CF9FE' // 0% 处的颜色
    },
    {
        offset: 0.17,
        color: '#468EFD' // 100% 处的颜色
    },
    {
        offset: 0.9,
        color: '#468EFD' // 100% 处的颜色
    },
    {
        offset: 1,
        color: '#5CF9FE' // 100% 处的颜色
    }
]);`

会出现以下error：
Uncaught (in promise) ReferenceError: echarts is not defined

请问要怎么引入echarts.js/mychart等封装呢？

**Comment by bugybq** [comment]
关注，我也有同样的问题，绘制自定义图形时会报同样的错误
```
    var rectShape = echarts.graphic.clipRectByRect({
        x: start[0],
        y: start[1] - height / 2,
        width: end[0] - start[0],
        height: height
    }, {
        x: params.coordSys.x,
        y: params.coordSys.y,
        width: params.coordSys.width,
        height: params.coordSys.height
    });
```

**Comment by tctdrb** [comment]
我试着去修改了module.js文件，
并在function (data, theme, echartsInstance)添加了一个参数echarts.
现在使用起来没有问题。

module.js修改如下：
1.function (data, theme, echartsInstance)改为function (data, theme, echartsInstance,echarts)
2.this.getOption(this.props.data, this.props.theme, this.chart)改为
this.getOption(this.props.data, this.props.theme, this.chart, g.a)


[module.zip](https://github.com/Billiballa/grafana-echarts/files/4709190/module.zip)

**Comment by Billiballa** [comment]
提交了新版本，参数里添加了eharts
