### ISSUE TITLE
显示插件not found

### ISSUE THREAD

**Issue by jishandong** [Billiballa/grafana-echarts#14]
1、按照步骤执行
git clone
cd pluging
yarn install
yarn dev
2、界面显示
![image](https://user-images.githubusercontent.com/13673915/83474045-9bed0f00-a4bd-11ea-9638-8c3e1aed9a2e.png)
请问这是什么问题呢？
grafana 版本6.3.x

谢谢~

**Comment by Billiballa** [comment]
直接clone下来 重启grafana 然后在新建的dashboard里尝试如何呢？

**Comment by jishandong** [comment]
我的插件路径是这个 /var/lib/grafana/plugins
按照您的操作试了一遍，依旧提示找不到
![image](https://user-images.githubusercontent.com/13673915/83603550-36754d00-a5a7-11ea-913f-b2e51bcd3c89.png)

**Comment by jishandong** [comment]
![image](https://user-images.githubusercontent.com/13673915/83603789-9d930180-a5a7-11ea-92b4-76687ea3e1d7.png)

**Comment by Billiballa** [comment]
项目是用官方提供的[@grafana/toolkit](https://www.npmjs.com/package/@grafana/toolkit)的7.0版本构建的，使用了新API不兼容旧版grafana，我之前没有仔细测试过。。

现在已经修复了，不过6.3.x的数据可能和7.0不一样，需要将'Grafana Option'选项中data的处理函数修改一下。
```
const sData = s.rows.map((f) => f[0]);
const sTime = s.rows.map((f) => f[1]);
```

**Comment by jishandong** [comment]
![image](https://user-images.githubusercontent.com/13673915/83737787-11a3d700-a686-11ea-91e5-239e86a91760.png)
更新了最新的代码，依旧不显示

**Comment by Billiballa** [comment]
如果控制台提示`Editor content error!`则没有正确配置编辑器内容。

编辑器的代码如何设置请看插件的默认配置和[使用方法](https://github.com/Billiballa/grafana-echarts/issues/11#issuecomment-635065678)。
