### ISSUE TITLE
刷新echart options时机

### ISSUE THREAD

**Issue by cauccyu** [Billiballa/grafana-echarts#16]
在function中第一行加上：
```
console.log(data);
```
然后可以看到刷新panel时function被调用了两次，第一次data的state是Loading状态，第二次则是Done状态：
![image](https://user-images.githubusercontent.com/30642287/84129425-860abb80-aa74-11ea-9d04-1d1f1b4ba7a7.png)

会导致一次刷新而图形加载两次，在一定的操作（如对data中的数据buffer做splice或者pop操作）下甚至会产生图形中数据的错误。
解决：可以在resetOption中加入对data.state的判断，如果不为Done则不触发echart刷新：
![image](https://user-images.githubusercontent.com/30642287/84129297-62e00c00-aa74-11ea-8dc4-039d2ca10987.png)

**Comment by Billiballa** [comment]
多谢~已采纳
