### ISSUE TITLE
Not working in Grafana 6.

### ISSUE THREAD

**Issue by LeonardoLeoLeal** [Billiballa/grafana-echarts#4]
Hello, I have installed the plugin with yarn, but when I try to use it on Grafana I get this error: Cannot use 'in' operator to search for '_ec_inner' in undefined. Can you help me please?

**Comment by Billiballa** [comment]
Is this error still present when running `yarn dev` ?

**Comment by karlie93** [comment]
I running yarn dev,still report this error:Cannot use 'in' operator to search for '_ec_inner' in undefined.

**Comment by Billiballa** [comment]
It has been fixed
