### ISSUE TITLE
I can't build your code, but `disk` works, Can you help me?

### ISSUE THREAD

**Issue by 0uzu0** [Billiballa/grafana-echarts#6]
node： v11.15.0
for example:
```
ERROR in C:\Users\zwx781856\Desktop\grafana-echarts-master\src\module.tsx(1,10)
grafana-echarts-master/node_modules/@grafana/ui"' has no exported member 'PanelPlugin'.
```
is it means `grafana/ui` --> `grafana/data`

**Comment by Billiballa** [comment]
more info see here: grafana/grafana#20338.
[In 6.5+ it is moved to '@grafana/data' -- until 7.0, it will also be exported at runtime to panels under @grafana/ui. See this semi-hack](https://github.com/grafana/grafana/issues/20338#issuecomment-553498978)
