### ISSUE TITLE
可否使用地图

### ISSUE THREAD

**Issue by dushang2016** [Billiballa/grafana-echarts#8]
这个插件可否实现地图的额绘制？我尝试的没成功，能否支持一下？谢谢

**Comment by Billiballa** [comment]
已经简单实现了，把地图的json文件加入**src/map**,  重新跑一遍build, 每次运行时会加载全部并按文件名注册。

**Comment by dushang2016** [comment]
> 已经简单实现了，把地图的json文件加入**src/map**, 重新跑一遍build, 每次运行时会加载全部并按文件名注册。

option={
    series: [{
                    type: 'map',
                    mapType: 'china',
                    label: {
                        normal: {
                            show:false,
                        },    
                        emphasis: {//对应的鼠标悬浮效果
                           show:false,
                            
                        } 
                    },
                    itemStyle: {
                        normal: {
                            borderWidth: 2,//区域边框宽度
                            borderColor: '#0083ce',//区域边框颜色
                            areaColor:"#0083ce",//区域颜色
                        },
                        emphasis: {
                            borderWidth: 0.4,
                            borderColor: 'black',
                            areaColor:"#0083ce",
                        }
                    },
                    data:[
                        {name:'云南', selected:true},//
                         {name:'广东', selected:true},//
                          {name:'浙江', selected:true}//
                    ]
                }],
            };  

我使用这个仍然不能work啊。您那可以么

**Comment by Billiballa** [comment]
尝试更换你自己的geoJSON, 项目中的来自 [geoJSON](https://gallery.echartsjs.com/editor.html?c=xmCAi_XNuJ).

附上一个🌰：
```javascript
return {
  backgroundColor: 'transparent',
  tooltip: {
    trigger: 'item',
    formatter: ({ name, value }) => `${name}: ${value}`
  },
  visualMap: {
    left: 'right',
    max: 500,
    inRange: {
      color: ['#313695', '#e0f3f8', '#a50026']
    },
    text: ['High', 'Low'],
    calculable: true
  },
  series: [
    {
      type: 'map',
      roam: true,
      map: 'china',
      data: [
        { name: '北京市', value: 434 },
        { name: '云南省', value: 123 },
        { name: '广东省', value: 234 },
        { name: '浙江省', value: 321 },
        { name: '黑龙江省', value: 324 },
        { name: '新疆维吾尔自治区', value: 421 }
      ]
    }
  ]
};
```

**Comment by dushang2016** [comment]
解决了，thx
